#!/usr/bin/env python3
import hashlib,importlib.util,json,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];E=ROOT/"internal-skills"/"minmax-enterprise-proposal";I=ROOT/"internal-skills"/"minmax-proposal-inquiry"
def load(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
pv=load("pv",I/"scripts"/"validate_profile.py");pr=load("pr",I/"scripts"/"profile_report.py");vp=load("vp",E/"scripts"/"validate_proposal.py");pf=load("pf",E/"scripts"/"preflight_proposal.py")
def profile():return {"schema_version":"1.0","status":"configured","business":{"name":"Northstar","category":"B2B advisory","one_liner":"Revenue systems.","default_currency":"USD","languages":["en"]},"positioning":{"ideal_customers":["B2B"],"core_problems":["Fragmented revenue"],"buyer_roles":["CRO"],"value_proposition":"Clarify the revenue operating model."},"offers":[{"id":"revenue-redesign","name":"Revenue Redesign","type":"project","business_value":"Clarify ownership.","deliverables":["Operating model"],"boundaries":["No CRM implementation"],"client_dependencies":["Sponsor"],"pricing":{"model":"fixed","currency":"USD","unit":"project","public_price":10000,"floor":10000}}],"commercial":{"proposal_validity_days":30,"default_payment_terms":"50/50","discount_policy":"No discount below floor.","scope_change_policy":"Re-estimate changes."},"proof":{"metrics":[{"id":"m1","claim":"Verified proof","source":"internal:proof:1","confidence":"verified"}],"case_studies":[],"testimonials":[],"customer_logos":[]},"brand":{"logo_path":"","primary_color":"#111827","accent_color":"#2563EB","background_color":"#F8FAFC","surface_color":"#FFFFFF","text_color":"#111827","muted_color":"#64748B","font_display":"Inter, sans-serif","font_body":"Inter, sans-serif","visual_style":["minimal"]},"voice":{"default_language":"en","tone":["specific"],"claim_policy":"Verified proof only."},"proposal_defaults":{"page_size":"A4-landscape","approval_mode":"thesis_first","default_next_step":"Align scope."}}
def proposal(rev=1):return {"schema_version":"1.0","meta":{"proposal_title":"Proposal","client_name":"Acme","release_mode":"autonomous","source_profile_revision":rev},"evidence_ledger":[{"id":"ev-1","class":"verified_client_fact","claim":"Acme has fragmented ownership.","source_ref":"deal:1","confidence":"verified"}],"pages":[{"type":"cover","section":"Proposal","title":"Revenue Redesign"},{"type":"proof","section":"Context","title":"What we know","evidence_ids":["ev-1"]},{"type":"commercial","section":"Investment","title":"Investment","investment":{"included_scope":["Redesign"],"assumptions":["One BU"],"rationale":"Fixed scope.","components":[{"label":"Fee","amount":"USD 10,000","amount_value":10000,"unit":"project","include_in_total":True}],"total":"USD 10,000","payment_terms":"50/50","calculation":{"status":"fixed","currency":"USD","total_value":10000}}},{"type":"next-step","section":"Next steps","title":"Next steps","next_step":"Confirm scope."}]}
p=profile();e,w=pv.validate(p);assert not e,e;scores,total,r=pr.score_profile(p);assert r=="configured",(scores,total,r);weak=profile();weak["offers"][0]["boundaries"]=[];assert pr.score_profile(weak)[2]!="configured";no_proof=profile();no_proof["proof"]={"metrics":[],"case_studies":[],"testimonials":[],"customer_logos":[]};e,_=pv.validate(no_proof);assert any("verified/approved proof" in x for x in e),e
with tempfile.TemporaryDirectory() as td:
 t=Path(td);pp=t/"p.json";sp=t/"s.json";pp.write_text(json.dumps(p),encoding="utf-8");sp.write_text(json.dumps({"schema_version":"1.0","configuration_revision":1,"profile_status":"configured","profile_sha256":hashlib.sha256(pp.read_bytes()).hexdigest()}),encoding="utf-8");data=proposal();e,w=vp.validate(data,pp,sp);assert not e,e;bad=proposal();bad["pages"][2]["investment"]["components"][0]["amount_value"]=9000;e,_=vp.validate(bad,pp,sp);assert any("component sum" in x for x in e),e;html='<section class="page cover"></section>'+'<section class="page"></section>'*3+' '*1200;e,_=pf.run_checks(html,data,None);assert any("visual QA" in x for x in e),e;visual={"status":"PASS","method":"browser_render","overflow":False,"clipping":False,"missing_assets":[]};e,_=pf.run_checks(html,data,visual);assert not e,e
print("PASS: MinMax Proposals reliability regression tests")
